# The clock and its 
set_property PACKAGE_PIN E3 [get_ports Clk]		
set_property IOSTANDARD LVCMOS33 [get_ports Clk]
# Competition Clock
create_clock -period 29.3 -name Clk -waveform {0.000 14.650} [get_ports Clk]
# Slowed Clock To Display Updates
#create_clock -period 1000000 -name Clk -waveform {0.000 500000} [get_ports Clk]

##The reset (upper push button)
set_property IOSTANDARD LVCMOS33 [get_ports Rst]
set_property PACKAGE_PIN F15 [get_ports Rst]

### FOR OUR FPGA BOARD ###
### This part is to activate or deactive ANODE of each display digit
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[0]}]
set_property PACKAGE_PIN N6 [get_ports {en_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[1]}]
set_property PACKAGE_PIN M6 [get_ports {en_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[2]}]
set_property PACKAGE_PIN M3 [get_ports {en_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[3]}]
set_property PACKAGE_PIN N5 [get_ports {en_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[4]}]
set_property PACKAGE_PIN N2 [get_ports {en_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[5]}]
set_property PACKAGE_PIN N4 [get_ports {en_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[6]}]
set_property PACKAGE_PIN L1 [get_ports {en_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {en_out[7]}]
set_property PACKAGE_PIN M1 [get_ports {en_out[7]}]

###This part is to assign pin numbers for 7 segments of the digit display
set_property IOSTANDARD LVCMOS33 [get_ports {out7[6]}]
set_property PACKAGE_PIN L3 [get_ports {out7[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out7[5]}]
set_property PACKAGE_PIN N1 [get_ports {out7[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out7[4]}]
set_property PACKAGE_PIN L5 [get_ports {out7[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out7[3]}]
set_property PACKAGE_PIN L4 [get_ports {out7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out7[2]}]
set_property PACKAGE_PIN K3 [get_ports {out7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out7[1]}]
set_property PACKAGE_PIN M2 [get_ports {out7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out7[0]}]
set_property PACKAGE_PIN L6 [get_ports {out7[0]}]

### FOR COMPETITION BOARD ###
## This part is to activate or deactive ANODE of each display digit
# IOSTANDARD LVCMOS33 [get_ports {en_out[0]}]
#set_property PACKAGE_PIN J17 [get_ports {en_out[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[1]}]
#set_property PACKAGE_PIN J18 [get_ports {en_out[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[2]}]
#set_property PACKAGE_PIN T9 [get_ports {en_out[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[3]}]
#set_property PACKAGE_PIN J14 [get_ports {en_out[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[4]}]
#set_property PACKAGE_PIN P14 [get_ports {en_out[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[5]}]
#set_property PACKAGE_PIN T14 [get_ports {en_out[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[6]}]
#set_property PACKAGE_PIN K2 [get_ports {en_out[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {en_out[7]}]
#set_property PACKAGE_PIN U13 [get_ports {en_out[7]}]

##This part is to assign pin numbers for 7 segments of the digit display
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[6]}]
#set_property PACKAGE_PIN T10 [get_ports {out7[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[5]}]
#set_property PACKAGE_PIN R10 [get_ports {out7[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[4]}]
#set_property PACKAGE_PIN K16 [get_ports {out7[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[3]}]
#set_property PACKAGE_PIN K13 [get_ports {out7[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[2]}]
#set_property PACKAGE_PIN P15 [get_ports {out7[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[1]}]
#set_property PACKAGE_PIN T11 [get_ports {out7[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {out7[0]}]
#set_property PACKAGE_PIN L18 [get_ports {out7[0]}]